spring:
  application:
    name: HR-monitor-backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/hr-monitor-db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 007787898
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8090
